version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 1s
      retries: 5
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 5
  backend-api:
    build: ./backend
    image: libray-system:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://user:password@postgres:5432/database
      REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  frontend-api:
    build: ./frontend
    image: library-system-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend-api