runtime: python39
service: library-system-backend
handlers:
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto
env_variables:
  SQLALCHEMY_DATABASE_URL: postgresql://user:password123@10.67.16.3:5432/database
  BUCKET_NAME: dg-library-2302-klaus
  PUBSUB_TOPIC: projects/thematic-garage-386114/topics/dg-library-system
  REDIS_HOST: 10.67.17.3
  REDIS_PORT: 6379

vpc_access_connector:
 name: projects/thematic-garage-386114/locations/asia-east2/connectors/connector