version: "3.9"
services:
  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
