version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
  backend-api:
    build: .
    image: libray-system:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://user:password@postgres:5432/database
      REDIS_HOST: redis
