apiVersion: v1
kind: Service
metadata:
  name: library-system
  labels:
    app: library-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: library-system
