"""Modify Document columns

Revision ID: aeee820bdfcd
Revises: ce83889306a2
Create Date: 2023-04-11 16:54:54.087409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from models import Document

# revision identifiers, used by Alembic.
revision = 'aeee820bdfcd'
down_revision = 'ce83889306a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('bucket_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('blob_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('presigned_url', sa.String(), nullable=True))
    op.drop_column('documents', 'gcs_uri')
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for document in session.query(Document).all():
        document.bucket_id = document.gcs_uri.split('/')[2]
        document.blob_id = document.gcs_uri.split('/')[3]
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('gcs_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for document in session.query(Document).all():
        document.gcs_uri = f'gs://{document.bucket_id}/{document.blob_id}'
    session.commit()
    op.drop_column('documents', 'presigned_url')
    op.drop_column('documents', 'blob_id')
    op.drop_column('documents', 'bucket_id')
